default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: awesome_pm_dev

test:
  <<: *default
  database: awesome_pm_test

production:
  <<: *default
  database: awesome_pm_prod
